name: CI Pipeline for Staff Microservice

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests and Linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20  

      - name: Verify Go Installation
        run: go version

      - name: Verify Go Modules
        run: go env GOPATH

      - name: Install Dependencies
        run: |
          cd $GITHUB_WORKSPACE  # Ensure we are in the correct project root
          ls -al  # Debugging: List files to check if go.mod exists
          go mod tidy

      - name: Run Tests
        run: go test ./...

      - name: Run GolangCI-Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
