name: golangci-lint

on:
  pull_request:

permissions:
  contents: read
  pull-requests: read
  checks: write

jobs:
  golangci:
    name: Lint & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22.1'
          cache: false

      - run: git config --global url."https://${{ secrets.ACTOR }}:${{ secrets.TOKEN }}@github.com/".insteadOf "https://github.com/"

      - name: Run GolangCI-Lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.57.1
          working-directory: server

      - name: Run Tests
        run: make test
