name: Run GolangCI-Lint and Makefile Test

on:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - main
      - develop

jobs:
  lint:
    name: Lint Code with GolangCI-Lint
    runs-on: ubuntu-latest

    env: 
      GO_VERSION: '1.24'
      GRPC_PORT: '50053'  
      AUTH_ISSUER: 'http://auth.BetterGR.org'  
      DSN: 'postgres://postgres:bettergr2425@localhost:5432/bettergr?sslmode=disable'  
      DP_NAME: 'bettergr'  

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go ${{ env.GO_VERSION }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install Dependencies
        run: |
          go mod tidy
          go mod download
          go mod vendor  # Ensure all dependencies are available

      - name: Run GolangCI-Lint
        run: golangci-lint run --timeout=5m

      - name: Setup Test Database  
        run: |
          sudo apt-get install -y postgresql
          sudo systemctl start postgresql
          sudo -u postgres psql -c "CREATE DATABASE bettergr;"
          sudo -u postgres psql -d bettergr -c "CREATE TABLE courses (id SERIAL PRIMARY KEY, name TEXT NOT NULL);"

      - name: Run Makefile Test with Environment Variables
        env:
          GRPC_PORT: '50053'  
          AUTH_ISSUER: 'http://auth.BetterGR.org'  
          DSN: 'postgres://postgres:bettergr2425@localhost:5432/bettergr?sslmode=disable'  
          DP_NAME: 'bettergr'  
        run: make test
