name: Run GolangCI-Lint

on:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - main
      - develop

jobs:
  lint:
    name: Lint Code with GolangCI-Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'  # Adjust to your Go version

      - name: Clean and Reset Dependencies
        run: |
          rm -rf ~/.cache/go-build
          rm -rf ~/go/pkg/mod
          go mod tidy
          go mod download

      - name: Install GolangCI-Lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.57.1
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Run GolangCI-Lint
        run: |
          golangci-lint run --timeout=5m
